export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_PLAYLIST = 'SET_PLAYLIST'
export const SET_BILLBOARD = 'SET_BILLBOARD'
export const SET_ALLPLAYLIST = 'SET_ALLPLAYLIST'
